postgres:
  host: localhost
  port: 32768
  user: teodor
  database: teodor
  password: markup
logger:
  logger_level: DEBUG
  format: '[{asctime}][{levelname}] - {name}: {message}'
  style: '{'
app:
  version: 1.0.0
  port:
    3010
