version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7.2
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: ./manage.py test
          name: Test

workflows:
  main:
    jobs:
      - build
