version: 2.1

orbs:
  python: circleci/python@0.2.1
defaults: &defaults
  working_directory: ~/deploy-project
aliases:
  - &digital-ocean
    name: digital-ocean
    command: ssh -o "StrictHostKeyChecking no" root@165.227.158.52 "cd ~/projects/swen-tech-backend; git stash; git pull; pip install -r requirements.txt;"
jobs:
  build:
    <<: *defaults
    docker:
      - image: circleci/python:3.7.2
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - add_ssh_keys:
            fingerprints:
              # ключ для доступа к целевой машине, на которую производится деплой
              - "ab:6b:83:e0:8b:38:50:9c:95:0b:b1:c6:7d:f5:ce:00"
      - run: *digital-ocean
workflows:
  main:
    jobs:
      - build
